# Default values for nodejs-mongo-app.

replicaCount: 1

image:
  DOCKER_IMAGE: "/nodejscrud:$ 7607bd9"
  pullPolicy: IfNotPresent
service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: false

resources: {}
  # Limits and requests for CPU and memory can be set here

env:
  MONGO_URI: "mongodb://root:password@mongo-service.default.svc.cluster.local:27017"  # Replace with your MongoDB URI

# Node.js specific environment variables and configurations
nodePort: 5000  # The port your app runs on inside the container
