name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch
  pull_request:

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Log in to ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      
      - name: Build and push Docker image to ECR
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}  # ECR repository URL
          COMMIT_HASH: ${{ github.sha }}  # Git commit hash
        run: |
          IMAGE_TAG="${COMMIT_HASH:0:7}"  # Truncate commit hash to 7 characters
          echo "Building Docker image with commit hash tag: $IMAGE_TAG"
          docker build -t $ECR_REGISTRY/nodejscrud:$IMAGE_TAG .
          docker push $ECR_REGISTRY/nodejscrud:$IMAGE_TAG

      - name: Update Helm Chart with new image tag
        env:
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REGISTRY: ${{ secrets.ECR_REGISTRY }}  # ECR repository URL
          COMMIT_HASH: ${{ github.sha }}  # Git commit hash
        run: |
          IMAGE_TAG="${COMMIT_HASH:0:7}"  # Use the same commit hash format here
          sed -i 's|<DOCKER_IMAGE>|$ECR_REGISTRY/nodejscrud:$IMAGE_TAG|' helm/nodejs-mongo-crud/values.yaml
          git add helm/nodejs-mongo-crud/values.yaml
          git commit -m "Update Helm chart with new image tag $IMAGE_TAG"
          git push origin main